name: Build & deploy

on:

  push:

    branches: [main]

jobs:

  deploy:
  
    runs-on: ubuntu-latest

    steps:

      - name: Deploy NodeJs app

        uses: appleboy/ssh-action@v0.1.2

        with:

          host: ${{secrets.SSH_HOST}}

          key: ${{secrets.SSH_KEY}}

          username: ${{secrets.SSH_USERNAME}}

          script: |

            mkdir test

            cd test

            git clone git@github.com:amineSQLi/digitalOcean-CICD.git

            echo 'Deployment succesful to digital ocean'
